/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright (C) 2021, KNS Group LLC (YADRO)
 */

#pragma once

#include <regex>

enum class ConnectorType
{
    SYSTEM,
    CPU,
    NONE
};

struct FanConDescription
{
    ConnectorType type;
    uint32_t fanIndex;
    std::string connector;
    std::string zone;
    uint32_t tachIndexA;
    uint32_t tachIndexB;
    uint32_t pwmIndex;
    uint32_t pwmLimitMax;
    std::string presencePinName;
};

static const std::map<size_t, FanConDescription> FanConnectorsN110 = {
    {1,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 1,
      .connector = "Fan 1",
      .zone = "Main",
      .tachIndexA = 0,
      .tachIndexB = 6,
      .pwmIndex = 0}},
    {2,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 2,
      .connector = "Fan 2",
      .zone = "Main",
      .tachIndexA = 1,
      .tachIndexB = 8,
      .pwmIndex = 1}},
    {3,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 3,
      .connector = "Fan 3",
      .zone = "Main",
      .tachIndexA = 2,
      .tachIndexB = 9,
      .pwmIndex = 2}},
    {4,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 4,
      .connector = "Fan 4",
      .zone = "Main",
      .tachIndexA = 3,
      .tachIndexB = 10,
      .pwmIndex = 3}},
    {5,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 5,
      .connector = "Fan 5",
      .zone = "Main",
      .tachIndexA = 4,
      .tachIndexB = 11,
      .pwmIndex = 4}},
    {6,
     {.type = ConnectorType::CPU,
      .fanIndex = 0,
      .connector = "J76",
      .zone = "CPU",
      .tachIndexA = 5,
      .tachIndexB = 0,
      .pwmIndex = 5}}};
static const std::map<size_t, FanConDescription> FanConnectorsS220 = {
    {1,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 1,
      .connector = "2U_F1",
      .zone = "Main",
      .tachIndexA = 0,
      .tachIndexB = 0,
      .pwmIndex = 0}},
    {2,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 2,
      .connector = "2U_F2",
      .zone = "Main",
      .tachIndexA = 1,
      .tachIndexB = 0,
      .pwmIndex = 1}},
    {3,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 3,
      .connector = "2U_F3",
      .zone = "Main",
      .tachIndexA = 2,
      .tachIndexB = 0,
      .pwmIndex = 2}},
    {4,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 4,
      .connector = "2U_F4",
      .zone = "Main",
      .tachIndexA = 3,
      .tachIndexB = 0,
      .pwmIndex = 3}},
    {5,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 5,
      .connector = "2U_F5",
      .zone = "Main",
      .tachIndexA = 4,
      .tachIndexB = 0,
      .pwmIndex = 4}},
    {6,
     {.type = ConnectorType::CPU,
      .fanIndex = 0,
      .connector = "J76",
      .zone = "CPU",
      .tachIndexA = 5,
      .tachIndexB = 0,
      .pwmIndex = 5}},
    {7,
     {.type = ConnectorType::CPU,
      .fanIndex = 1,
      .connector = "J75",
      .zone = "CPU",
      .tachIndexA = 6,
      .tachIndexB = 0,
      .pwmIndex = 6}}};
static const std::map<size_t, FanConDescription> FanConnectorsS320 = {
    {1,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 1,
      .connector = "3U_F1",
      .zone = "Main",
      .tachIndexA = 0,
      .tachIndexB = 0,
      .pwmIndex = 0}},
    {2,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 2,
      .connector = "3U_F2",
      .zone = "Main",
      .tachIndexA = 1,
      .tachIndexB = 0,
      .pwmIndex = 1}},
    {3,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 3,
      .connector = "3U_F3",
      .zone = "Main",
      .tachIndexA = 2,
      .tachIndexB = 0,
      .pwmIndex = 2}},
    {4,
     {.type = ConnectorType::NONE,
      .fanIndex = 4,
      .connector = "2U_F4",
      .zone = "Main",
      .tachIndexA = 3,
      .tachIndexB = 0,
      .pwmIndex = 3}},
    {5,
     {.type = ConnectorType::NONE,
      .fanIndex = 5,
      .connector = "2U_F5",
      .zone = "Main",
      .tachIndexA = 4,
      .tachIndexB = 0,
      .pwmIndex = 4}},
    {6,
     {.type = ConnectorType::CPU,
      .fanIndex = 0,
      .connector = "J76",
      .zone = "CPU",
      .tachIndexA = 5,
      .tachIndexB = 0,
      .pwmIndex = 5}},
    {7,
     {.type = ConnectorType::CPU,
      .fanIndex = 1,
      .connector = "J75",
      .zone = "CPU",
      .tachIndexA = 6,
      .tachIndexB = 0,
      .pwmIndex = 6}}};
static const std::map<size_t, FanConDescription> FanConnectorsR120 = {
    {1,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 0,
      .connector = "Fan0",
      .zone = "Main",
      .tachIndexA = 1,
      .tachIndexB = 8,
      .pwmIndex = 1,
      .pwmLimitMax = 80}},
    {2,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 1,
      .connector = "Fan1",
      .zone = "Main",
      .tachIndexA = 2,
      .tachIndexB = 9,
      .pwmIndex = 2}},
    {3,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 2,
      .connector = "Fan2",
      .zone = "Main",
      .tachIndexA = 0,
      .tachIndexB = 7,
      .pwmIndex = 0,
      .pwmLimitMax = 80}},
    {4,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 3,
      .connector = "Fan3",
      .zone = "Main",
      .tachIndexA = 4,
      .tachIndexB = 11,
      .pwmIndex = 4,
      .pwmLimitMax = 80}},
    {5,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 4,
      .connector = "Fan4",
      .zone = "Main",
      .tachIndexA = 5,
      .tachIndexB = 12,
      .pwmIndex = 5}},
    {6,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 5,
      .connector = "Fan5",
      .zone = "Main",
      .tachIndexA = 3,
      .tachIndexB = 10,
      .pwmIndex = 3}},
    {7,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 6,
      .connector = "Fan6",
      .zone = "Main",
      .tachIndexA = 6,
      .tachIndexB = 13,
      .pwmIndex = 6,
      .pwmLimitMax = 86}},
};
static const std::map<size_t, FanConDescription> FanConnectorsR120G2 = {
    {1,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 0,
      .connector = "Fan0",
      .zone = "Main",
      .tachIndexA = 0,
      .tachIndexB = 7,
      .pwmIndex = 0,
      .presencePinName = "SYS_FAN0_PRSNT"}},
    {2,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 1,
      .connector = "Fan1",
      .zone = "Main",
      .tachIndexA = 1,
      .tachIndexB = 8,
      .pwmIndex = 1,
      .presencePinName = "SYS_FAN1_PRSNT"}},
    {3,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 2,
      .connector = "Fan2",
      .zone = "Main",
      .tachIndexA = 2,
      .tachIndexB = 9,
      .pwmIndex = 2,
      .presencePinName = "SYS_FAN2_PRSNT"}},
    {4,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 3,
      .connector = "Fan3",
      .zone = "Main",
      .tachIndexA = 3,
      .tachIndexB = 10,
      .pwmIndex = 3,
      .presencePinName = "SYS_FAN3_PRSNT"}},
    {5,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 4,
      .connector = "Fan4",
      .zone = "Main",
      .tachIndexA = 4,
      .tachIndexB = 11,
      .pwmIndex = 4,
      .presencePinName = "SYS_FAN4_PRSNT"}},
    {6,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 5,
      .connector = "Fan5",
      .zone = "Main",
      .tachIndexA = 5,
      .tachIndexB = 12,
      .pwmIndex = 5,
      .presencePinName = "SYS_FAN5_PRSNT"}},
    {7,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 6,
      .connector = "Fan6",
      .zone = "Main",
      .tachIndexA = 6,
      .tachIndexB = 13,
      .pwmIndex = 6,
      .presencePinName = "SYS_FAN6_PRSNT"}},
};
static const std::map<size_t, FanConDescription> FanConnectorsR220G2 = {
    {1,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 0,
      .connector = "Fan0",
      .zone = "Main",
      .tachIndexA = 0,
      .tachIndexB = 0,
      .pwmIndex = 0,
      .presencePinName = "SYS_FAN0_PRSNT"}},
    {2,
     {.type = ConnectorType::NONE,
      .fanIndex = 0,
      .connector = "Fan1",
      .zone = "Main",
      .tachIndexA = 1,
      .tachIndexB = 0,
      .pwmIndex = 1}},
    {3,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 1,
      .connector = "Fan2",
      .zone = "Main",
      .tachIndexA = 2,
      .tachIndexB = 0,
      .pwmIndex = 2,
      .presencePinName = "SYS_FAN2_PRSNT"}},
    {4,
     {.type = ConnectorType::NONE,
      .fanIndex = 1,
      .connector = "Fan3",
      .zone = "Main",
      .tachIndexA = 3,
      .tachIndexB = 0,
      .pwmIndex = 3}},
    {5,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 2,
      .connector = "Fan4",
      .zone = "Main",
      .tachIndexA = 4,
      .tachIndexB = 0,
      .pwmIndex = 4,
      .presencePinName = "SYS_FAN4_PRSNT"}},
    {6,
     {.type = ConnectorType::NONE,
      .fanIndex = 2,
      .connector = "Fan5",
      .zone = "Main",
      .tachIndexA = 5,
      .tachIndexB = 0,
      .pwmIndex = 5}},
    {7,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 3,
      .connector = "Fan6",
      .zone = "Main",
      .tachIndexA = 6,
      .tachIndexB = 0,
      .pwmIndex = 6,
      .presencePinName = "SYS_FAN6_PRSNT"}},
};
static const std::map<size_t, FanConDescription> FanConnectorsNicoleX86 = {
    {1,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 5,
      .connector = "Fan5",
      .zone = "Main",
      .tachIndexA = 5,
      .tachIndexB = 0,
      .pwmIndex = 5}},
};

enum class FanPerformanceType
{
    UNKNOWN,
    STANDARD,
    HIGH,
};

struct FanModuleInfo
{
    FanPerformanceType type{FanPerformanceType::UNKNOWN};
    uint32_t inletRangeMin{0};
    uint32_t inletRangeMax{0};
    uint32_t outletRangeMin{0};
    uint32_t outletRangeMax{0};
    std::string partNumber;
    std::string prettyName;
};

static const std::vector<FanModuleInfo> EmptyDetectionFanTable = {};

static const std::vector<FanModuleInfo> VegmanRx20DetectionFanTable = {
    {.type = FanPerformanceType::STANDARD,
     .inletRangeMin = 19000,
     .inletRangeMax = 24000,
     .outletRangeMin = 16200,
     .outletRangeMax = 19800,
     .partNumber = "ASMFAN783104A",
     .prettyName = "Standard performance fan"},
    {.type = FanPerformanceType::HIGH,
     .inletRangeMin = 26550,
     .inletRangeMax = 34000,
     .outletRangeMin = 22950,
     .outletRangeMax = 30800,
     .partNumber = "ASMFAN781104A1",
     .prettyName = "High performance fan"}};

struct ProductDescription
{
    std::regex pnameRegex;
    std::string productName;
    const std::map<size_t, FanConDescription>& fans;
    const std::vector<FanModuleInfo>& detectionFanTable{EmptyDetectionFanTable};
    std::string sysFanPN;
    std::string cpuFanPN;
};

static const std::vector<ProductDescription> productRegistry = {
    {.pnameRegex = std::regex("VEGMAN N110.*"),
     .productName = "VEGMAN N110",
     .fans = FanConnectorsN110,
     .sysFanPN = "ASMFAN781101A",
     .cpuFanPN = "CPUHSN792004A"},
    {.pnameRegex = std::regex("VEGMAN S220.*"),
     .productName = "VEGMAN S220",
     .fans = FanConnectorsS220,
     .sysFanPN = "ASMFAN781102A",
     .cpuFanPN = "CPUHSN792004A"},
    {.pnameRegex = std::regex("VEGMAN S320.*"),
     .productName = "VEGMAN S320",
     .fans = FanConnectorsS320,
     .sysFanPN = "ASMFAN781103A",
     .cpuFanPN = "CPUHSN792004A"},
    {.pnameRegex = std::regex("VEGMAN R120(?! G\\d).*"),
     .productName = "VEGMAN R120",
     .fans = FanConnectorsR120,
     .detectionFanTable = VegmanRx20DetectionFanTable,
     .sysFanPN = "ASMFAN781104A"},
    {.pnameRegex = std::regex("VEGMAN R120 G2.*"),
     .productName = "VEGMAN R120 G2",
     .fans = FanConnectorsR120G2,
     .sysFanPN = "MODFAN781001A"},
    {.pnameRegex = std::regex("VEGMAN R220 G2.*"),
     .productName = "VEGMAN R220 G2",
     .fans = FanConnectorsR220G2,
     .sysFanPN = "MODFAN781002A"},
    {.pnameRegex = std::regex("TATLIN\\.ARCHIVE\\.XS.*"),
     .productName = "TATLIN.ARCHIVE.XS",
     .fans = FanConnectorsS220,
     .sysFanPN = "ASMFAN781102A",
     .cpuFanPN = "CPUHSN792004A"},
    {.pnameRegex = std::regex("TATLIN\\.ARCHIVE\\.S.*"),
     .productName = "TATLIN.ARCHIVE.S",
     .fans = FanConnectorsS320,
     .sysFanPN = "ASMFAN781103A",
     .cpuFanPN = "CPUHSN792004A"},
    {.pnameRegex = std::regex("TATLIN.UNIFIED Gen2.*"),
     .productName = "TATLIN.UNIFIED Gen2",
     .fans = FanConnectorsNicoleX86,
     .sysFanPN = "NODE_SYS_FAN"}};
