/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright (C) 2021 YADRO.
 */

#pragma once

#include <regex>

enum class ConnectorType
{
    SYSTEM,
    CPU,
    NONE
};

struct FanConDescription
{
    ConnectorType type;
    uint32_t fanIndex;
    std::string connector;
    std::string zone;
    uint32_t tachIndexA;
    uint32_t tachIndexB;
    uint32_t pwmIndex;
    uint32_t pwmLimitMax;
};

static const std::map<size_t, FanConDescription> FanConnectorsN110 = {
    {1,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 1,
      .connector = "Fan 1",
      .zone = "Main",
      .tachIndexA = 0,
      .tachIndexB = 6,
      .pwmIndex = 0}},
    {2,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 2,
      .connector = "Fan 2",
      .zone = "Main",
      .tachIndexA = 1,
      .tachIndexB = 8,
      .pwmIndex = 1}},
    {3,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 3,
      .connector = "Fan 3",
      .zone = "Main",
      .tachIndexA = 2,
      .tachIndexB = 9,
      .pwmIndex = 2}},
    {4,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 4,
      .connector = "Fan 4",
      .zone = "Main",
      .tachIndexA = 3,
      .tachIndexB = 10,
      .pwmIndex = 3}},
    {5,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 5,
      .connector = "Fan 5",
      .zone = "Main",
      .tachIndexA = 4,
      .tachIndexB = 11,
      .pwmIndex = 4}},
    {6,
     {.type = ConnectorType::CPU,
      .fanIndex = 0,
      .connector = "J76",
      .zone = "CPU",
      .tachIndexA = 5,
      .tachIndexB = 0,
      .pwmIndex = 5}}};
static const std::map<size_t, FanConDescription> FanConnectorsS220 = {
    {1,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 1,
      .connector = "2U_F1",
      .zone = "Main",
      .tachIndexA = 0,
      .tachIndexB = 0,
      .pwmIndex = 0}},
    {2,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 2,
      .connector = "2U_F2",
      .zone = "Main",
      .tachIndexA = 1,
      .tachIndexB = 0,
      .pwmIndex = 1}},
    {3,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 3,
      .connector = "2U_F3",
      .zone = "Main",
      .tachIndexA = 2,
      .tachIndexB = 0,
      .pwmIndex = 2}},
    {4,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 4,
      .connector = "2U_F4",
      .zone = "Main",
      .tachIndexA = 3,
      .tachIndexB = 0,
      .pwmIndex = 3}},
    {5,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 5,
      .connector = "2U_F5",
      .zone = "Main",
      .tachIndexA = 4,
      .tachIndexB = 0,
      .pwmIndex = 4}},
    {6,
     {.type = ConnectorType::CPU,
      .fanIndex = 0,
      .connector = "J76",
      .zone = "CPU",
      .tachIndexA = 5,
      .tachIndexB = 0,
      .pwmIndex = 5}},
    {7,
     {.type = ConnectorType::CPU,
      .fanIndex = 1,
      .connector = "J75",
      .zone = "CPU",
      .tachIndexA = 6,
      .tachIndexB = 0,
      .pwmIndex = 6}}};
static const std::map<size_t, FanConDescription> FanConnectorsS320 = {
    {1,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 1,
      .connector = "3U_F1",
      .zone = "Main",
      .tachIndexA = 0,
      .tachIndexB = 0,
      .pwmIndex = 0}},
    {2,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 2,
      .connector = "3U_F2",
      .zone = "Main",
      .tachIndexA = 1,
      .tachIndexB = 0,
      .pwmIndex = 1}},
    {3,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 3,
      .connector = "3U_F3",
      .zone = "Main",
      .tachIndexA = 2,
      .tachIndexB = 0,
      .pwmIndex = 2}},
    {4,
     {.type = ConnectorType::NONE,
      .fanIndex = 4,
      .connector = "2U_F4",
      .zone = "Main",
      .tachIndexA = 3,
      .tachIndexB = 0,
      .pwmIndex = 3}},
    {5,
     {.type = ConnectorType::NONE,
      .fanIndex = 5,
      .connector = "2U_F5",
      .zone = "Main",
      .tachIndexA = 4,
      .tachIndexB = 0,
      .pwmIndex = 4}},
    {6,
     {.type = ConnectorType::CPU,
      .fanIndex = 0,
      .connector = "J76",
      .zone = "CPU",
      .tachIndexA = 5,
      .tachIndexB = 0,
      .pwmIndex = 5}},
    {7,
     {.type = ConnectorType::CPU,
      .fanIndex = 1,
      .connector = "J75",
      .zone = "CPU",
      .tachIndexA = 6,
      .tachIndexB = 0,
      .pwmIndex = 6}}};
static const std::map<size_t, FanConDescription> FanConnectorsR120 = {
    {1,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 1,
      .connector = "Fan1",
      .zone = "Main",
      .tachIndexA = 1,
      .tachIndexB = 8,
      .pwmIndex = 1,
      .pwmLimitMax = 80}},
    {2,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 2,
      .connector = "Fan2",
      .zone = "Main",
      .tachIndexA = 2,
      .tachIndexB = 9,
      .pwmIndex = 2}},
    {3,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 3,
      .connector = "Fan3",
      .zone = "Main",
      .tachIndexA = 0,
      .tachIndexB = 7,
      .pwmIndex = 0,
      .pwmLimitMax = 80}},
    {4,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 4,
      .connector = "Fan4",
      .zone = "Main",
      .tachIndexA = 4,
      .tachIndexB = 11,
      .pwmIndex = 4,
      .pwmLimitMax = 80}},
    {5,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 5,
      .connector = "Fan5",
      .zone = "Main",
      .tachIndexA = 5,
      .tachIndexB = 12,
      .pwmIndex = 5}},
    {6,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 6,
      .connector = "Fan6",
      .zone = "Main",
      .tachIndexA = 3,
      .tachIndexB = 10,
      .pwmIndex = 3}},
    {7,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 7,
      .connector = "Fan7",
      .zone = "Main",
      .tachIndexA = 6,
      .tachIndexB = 13,
      .pwmIndex = 6,
      .pwmLimitMax = 86}},
};
static const std::map<size_t, FanConDescription> FanConnectorsR220 = {
    {1,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 1,
      .connector = "Fan1",
      .zone = "Main",
      .tachIndexA = 1,
      .tachIndexB = 8,
      .pwmIndex = 1}},
    {2,
     {.type = ConnectorType::NONE,
      .fanIndex = 2,
      .connector = "Fan2",
      .zone = "Main",
      .tachIndexA = 2,
      .tachIndexB = 9,
      .pwmIndex = 2}},
    {3,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 3,
      .connector = "Fan3",
      .zone = "Main",
      .tachIndexA = 0,
      .tachIndexB = 7,
      .pwmIndex = 0}},
    {4,
     {.type = ConnectorType::NONE,
      .fanIndex = 4,
      .connector = "Fan4",
      .zone = "Main",
      .tachIndexA = 4,
      .tachIndexB = 11,
      .pwmIndex = 4}},
    {5,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 5,
      .connector = "Fan5",
      .zone = "Main",
      .tachIndexA = 5,
      .tachIndexB = 12,
      .pwmIndex = 5}},
    {6,
     {.type = ConnectorType::NONE,
      .fanIndex = 6,
      .connector = "Fan6",
      .zone = "Main",
      .tachIndexA = 3,
      .tachIndexB = 10,
      .pwmIndex = 3}},
    {7,
     {.type = ConnectorType::SYSTEM,
      .fanIndex = 7,
      .connector = "Fan7",
      .zone = "Main",
      .tachIndexA = 6,
      .tachIndexB = 13,
      .pwmIndex = 6}},
};

struct ProductDescription
{
    std::regex pnameRegex;
    std::string productName;
    const std::map<size_t, FanConDescription>& fans;
    std::string sysFanPN;
    std::string cpuFanPN;
};

static const std::vector<ProductDescription> productRegistry = {
    {.pnameRegex = std::regex("VEGMAN N110.*"),
     .productName = "VEGMAN N110",
     .fans = FanConnectorsN110,
     .sysFanPN = "ASMFAN781101A",
     .cpuFanPN = "CPUHSN792004A"},
    {.pnameRegex = std::regex("VEGMAN S220.*"),
     .productName = "VEGMAN S220",
     .fans = FanConnectorsS220,
     .sysFanPN = "ASMFAN781102A",
     .cpuFanPN = "CPUHSN792004A"},
    {.pnameRegex = std::regex("VEGMAN S320.*"),
     .productName = "VEGMAN S320",
     .fans = FanConnectorsS320,
     .sysFanPN = "ASMFAN781103A",
     .cpuFanPN = "CPUHSN792004A"},
    {.pnameRegex = std::regex("VEGMAN R120.*"),
     .productName = "VEGMAN R120",
     .fans = FanConnectorsR120,
     .sysFanPN = "ASMFAN781101A"},
    {.pnameRegex = std::regex("VEGMAN R220.*"),
     .productName = "VEGMAN R220",
     .fans = FanConnectorsR220,
     .sysFanPN = "ASMFAN781102A"},
    {.pnameRegex = std::regex("TATLIN\\.ARCHIVE\\.XS.*"),
     .productName = "TATLIN.ARCHIVE.XS",
     .fans = FanConnectorsS220,
     .sysFanPN = "ASMFAN781102A",
     .cpuFanPN = "CPUHSN792004A"},
    {.pnameRegex = std::regex("TATLIN\\.ARCHIVE\\.S.*"),
     .productName = "TATLIN.ARCHIVE.S",
     .fans = FanConnectorsS320,
     .sysFanPN = "ASMFAN781103A",
     .cpuFanPN = "CPUHSN792004A"}};
